cm:add_first_tick_callback(function()
    local faction_key = cm:get_local_faction_name(true)
    cm:treasury_mod(faction_key, 10000)
    out("[UNLOCK_DRAGONSHIPS] Script loaded. Added 10000 gold to " .. tostring(faction_key))
end)
